#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : R-BradleyTerry2
Version  : 1.1.3
Release  : 50
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/BradleyTerry2_1.1.3.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/BradleyTerry2_1.1.3.tar.gz
Summary  : Bradley-Terry Models
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-brglm
Requires: R-gtools
Requires: R-lme4
Requires: R-qvcalc
BuildRequires : R-brglm
BuildRequires : R-gnm
BuildRequires : R-gtools
BuildRequires : R-lme4
BuildRequires : R-qvcalc
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
versions in which the parameters are related to explanatory variables
    through a linear predictor and versions with contest-specific effects,
    such as a home advantage.

%prep
%setup -q -n BradleyTerry2
pushd ..
cp -a BradleyTerry2 buildavx2
popd
pushd ..
cp -a BradleyTerry2 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744382008

%install
export SOURCE_DATE_EPOCH=1744382008
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/BradleyTerry2/CITATION
/usr/lib64/R/library/BradleyTerry2/DESCRIPTION
/usr/lib64/R/library/BradleyTerry2/INDEX
/usr/lib64/R/library/BradleyTerry2/Meta/Rd.rds
/usr/lib64/R/library/BradleyTerry2/Meta/data.rds
/usr/lib64/R/library/BradleyTerry2/Meta/features.rds
/usr/lib64/R/library/BradleyTerry2/Meta/hsearch.rds
/usr/lib64/R/library/BradleyTerry2/Meta/links.rds
/usr/lib64/R/library/BradleyTerry2/Meta/nsInfo.rds
/usr/lib64/R/library/BradleyTerry2/Meta/package.rds
/usr/lib64/R/library/BradleyTerry2/Meta/vignette.rds
/usr/lib64/R/library/BradleyTerry2/NAMESPACE
/usr/lib64/R/library/BradleyTerry2/NEWS.md
/usr/lib64/R/library/BradleyTerry2/R/BradleyTerry2
/usr/lib64/R/library/BradleyTerry2/R/BradleyTerry2.rdb
/usr/lib64/R/library/BradleyTerry2/R/BradleyTerry2.rdx
/usr/lib64/R/library/BradleyTerry2/WORDLIST
/usr/lib64/R/library/BradleyTerry2/data/Rdata.rdb
/usr/lib64/R/library/BradleyTerry2/data/Rdata.rds
/usr/lib64/R/library/BradleyTerry2/data/Rdata.rdx
/usr/lib64/R/library/BradleyTerry2/doc/BradleyTerry.R
/usr/lib64/R/library/BradleyTerry2/doc/BradleyTerry.Rmd
/usr/lib64/R/library/BradleyTerry2/doc/BradleyTerry.html
/usr/lib64/R/library/BradleyTerry2/doc/index.html
/usr/lib64/R/library/BradleyTerry2/help/AnIndex
/usr/lib64/R/library/BradleyTerry2/help/BradleyTerry2.rdb
/usr/lib64/R/library/BradleyTerry2/help/BradleyTerry2.rdx
/usr/lib64/R/library/BradleyTerry2/help/aliases.rds
/usr/lib64/R/library/BradleyTerry2/help/paths.rds
/usr/lib64/R/library/BradleyTerry2/html/00Index.html
/usr/lib64/R/library/BradleyTerry2/html/R.css
/usr/lib64/R/library/BradleyTerry2/tests/old-tests/old-tests.R
/usr/lib64/R/library/BradleyTerry2/tests/testthat.R
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/add1.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/drop1.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/flatlizards-BTmodel.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/flatlizards-abilities.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/flatlizards-pred0-new.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/flatlizards-pred0-rainy.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/flatlizards-pred1-rainy.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/flatlizards-residuals.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/outputs/nested.rds
/usr/lib64/R/library/BradleyTerry2/tests/testthat/test-BTabilities.R
/usr/lib64/R/library/BradleyTerry2/tests/testthat/test-add1-drop1.R
/usr/lib64/R/library/BradleyTerry2/tests/testthat/test-baseball.R
/usr/lib64/R/library/BradleyTerry2/tests/testthat/test-countsToBinomial.R
/usr/lib64/R/library/BradleyTerry2/tests/testthat/test-flatlizards.R
/usr/lib64/R/library/BradleyTerry2/tests/testthat/test-nested.R
/usr/lib64/R/library/BradleyTerry2/tests/testthat/test-predict.R
